"""Added fields to User model

Revision ID: 3cfb6aba7be5
Revises: 0f8a890711fb
Create Date: 2024-01-12 14:21:42.283965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cfb6aba7be5'
down_revision = '0f8a890711fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_authenticated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_anonymous', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_anonymous')
        batch_op.drop_column('is_authenticated')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
